### ISSUE TITLE
1.1.1 => 1.2.0 results in errors when AD User account begin with #

### ISSUE THREAD

**Issue by catt231** [microsoft/terraform-provider-azuredevops#1123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v1.9.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.53.1
+ provider registry.terraform.io/hashicorp/azurerm v3.114.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.31.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/microsoft/azuredevops v1.2.0

```

### Affected Resource(s)

* `azuredevops_users`

### Terraform Configuration Files

```hcl
data "azuread_group" "Group" {
  display_name = "Group"
}

data "azuredevops_users" "group-users" {
  for_each  = toset(data.azuread_group.Group.members)
  origin    = "aad"
  origin_id = each.value
}
```

### Expected Behavior

```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes
are needed.
```

### Actual Behavior

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error:  User not found. Origin ID: 60adede4-c04d-40d2-86e5-952ff9766397
│ 
│   with data.azuredevops_users.group-users["60adede4-c04d-40d2-86e5-952ff9766397"],
│   on main.tf line 47, in data "azuredevops_users" "group-users":
│   47: data "azuredevops_users" "group-users" {
```

### Steps to Reproduce

1. Have a user in AD Group with format #user@domain.com
2. run `terraform apply` in 1.1.1 and it will work
1. run `terraform apply` in 1.2.0 and it will fail

**Comment by xuzhang3** [comment]
@catt231 this issue has been fixed in #1116

**Comment by catt231** [comment]
@xuzhang3 I'm still seeing the error running the code today. 

1.1.1 runs with no changes in plan, switch to branch with 1.2.0 and I get that error.

Are there any more details I can provide to help solve this issue?

Can I get it opened back up please

**Comment by xuzhang3** [comment]
@catt231  the patch not released, will be available in v1.3.0.   You can downgrade to `v1.1.1` or make sure the user exists in the ADO organization
