### ISSUE TITLE
Add support for service hooks

### ISSUE THREAD

**Issue by richardgavel** [microsoft/terraform-provider-azuredevops#203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support to maintain service hooks (specifically webhooks)

### New or Affected Resource(s)

* azuredevops_webhook

### Potential Terraform Configuration

```hcl
```

**Comment by xuzhang3** [comment]
[REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/hooks/?view=azure-devops-rest-5.1)

**Comment by richardgavel** [comment]
I can see why this hasn't been done yet. All the various kinds of triggers each require a potentially different block (buildCompleted vs codePushed vs etc). I'm starting to put it together myself, using serviceendpoint as a model

```
azuredevops_servicehook_webhook XXX
{
  trigger = "codePushed"

  codePushedTrigger = {
    repository = XXX
    branchName = XXX
    pushedBy = XXX
  }

  action = "HttpPost"

  httpPost ={
    url = ""
    etc..
  }
}
```

The trigger and the potential trigger block settings would be in the base, the other properties unique to the action would be in the each of the resource_servicehook_XXX resources (webhook vs slack vs etc, though I am only going to try and do webhook).

**Comment by stobias123** [comment]
Bump! Really need this feature!

**Comment by jamiejackson** [comment]
Did you get anywhere with it, @richardgavel ?

**Comment by fernandosalomao** [comment]
https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/servicehooks/client.go

**Comment by xuzhang3** [comment]
Supported resource: [azuredevops_servicehook_storage_queue_pipelines](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/servicehook_storage_queue_pipelines)

**Comment by symnatbay** [comment]
Even just a service hook for a custom webhook target and its events would be very helpful for managing custom integrations in large organizations.

**Comment by magodo** [comment]
Fixed by #1412

**Comment by symnatbay** [comment]
Sorry to bring this up again - there are other service hook types besides "tfs", is there any plan to support them? The service hook integration is incomplete without them, and I still cannot manage all of our org's service hooks with Terraform. There is [another PR](https://github.com/microsoft/terraform-provider-azuredevops/pull/1417) that looked like it addressed support for all hooks, which is what this issue's acceptance should have been hinged on.
